### ISSUE TITLE
Fine tune model for using on grayscale images of xview

### ISSUE THREAD

**Issue by sawhney-medha** [ultralytics/xview-yolov3#13]
I want to fine tune this model on a different dataset that is grayscale. I understand that train.py has a resume option which will start training from previous weights.  But train.py also uses target_c60.mat. I cannot understand how to create the .mat files for my own custom data. Please help

**Comment by glenn-jocher** [comment]
@sawhney-medha Hello, thank you for your interest in our work! Please note that this repository is no longer actively maintained. Instead we recommend all users start from github.com/ultralytics/yolov3 and adapt it to their specific needs.

The target_c60.mat file you mentioned can be read by scipy.io, however it was generated by a seperate MATLAB script, which mainly trims poor labels and creates a k-means anchors from the remaining good candidates.
https://github.com/ultralytics/xview-yolov3/blob/9d30dabaeccf7937d2e66dca7324890d65e1799b/utils/analysis.m#L79

In order to adapt github.com/ultralytics/yolov3 to geospatial data similar to xview you mainly need to implement the sliding window inference and chip training, and ideally also do a k-means search of your anchors.

**Comment by sawhney-medha** [comment]
Okay, Thank you.

**Comment by glenn-jocher** [comment]
Great, you're welcome!
